on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Lint
        run: pnpm run lint
      - name: Format
        run: pnpm run format
      - name: Type Check
        run: pnpm run type-check
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test:unit